# Generated by Django 5.1.1 on 2024-09-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='investigate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientdata',
            name='schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
