# Generated by Django 5.1.1 on 2024-09-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_clientdata_investigate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdata',
            name='assigned_user',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
