# Generated by Django 5.1.1 on 2024-09-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usersubmits'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmits',
            name='reviewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubmits',
            name='assigned_user',
            field=models.CharField(max_length=15),
        ),
    ]
